### ISSUE TITLE
A fatal error was encountered

### ISSUE THREAD

**Issue by matvejs16** [fpaezf/cs2-vpk-map-unpacker#1]
```cli
Cannot use file stream for [C:\Users\matve\Desktop\MapUnPacker\MapUnPacker.deps.json]: No such file or directory
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet\'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'C:\Users\matve\Desktop\MapUnPacker\MapUnPacker.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the 'C:\Users\matve\Desktop\MapUnPacker\MapUnPacker.runtimeconfig.json' file and specify the appropriate framework.
```

**Comment by fpaezf** [comment]
Download the latest version (v1.1): https://github.com/fpaezf/cs2-vpk-map-unpacker/releases/download/v1.1/MapUnPackerv1.1.zip

New release includes some json missing files. If it not fixes the issue, please download and install .NET 6 runtime: https://dotnet.microsoft.com/es-es/download/dotnet/6.0

Let me know if bug is fixed.

**Comment by matvejs16** [comment]
> Download the latest version (v1.1): https://github.com/fpaezf/cs2-vpk-map-unpacker/releases/download/v1.1/MapUnPackerv1.1.zip
> 
> New release includes some json missing files. If it not fixes the issue, please download and install .NET 6 runtime: https://dotnet.microsoft.com/es-es/download/dotnet/6.0
> 
> Let me know if bug is fixed.

Got new error
![image](https://github.com/fpaezf/cs2-vpk-map-unpacker/assets/74150728/947605ea-4cb0-4f48-9815-31e585a88392)

**Comment by fpaezf** [comment]
Some VPK files are just raw data and cannot be unpacked, try to unpack the root or main file called **pak01_dir.vpk** instead.

**Comment by matvejs16** [comment]
> Some VPK files are just raw data and cannot be unpacked, try to unpack the root or main file called **pak01_dir.vpk** instead.

You'r right! Works now!

**Comment by matvejs16** [comment]
@fpaezf, I have one more question.
I'm not familliar with vpk files and could't imagine what interesting can be there, maybe some API endpoins or theese kind of stuff, have you noticed there something that and maybe you can share some examples?
